import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const buildTimestamp = () => {
  const date = new Date()
  const parts = new Intl.DateTimeFormat('sv-SE', {
    timeZone: 'Etc/GMT-1',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false
  }).formatToParts(date)

  const map = Object.fromEntries(parts.map(part => [part.type, part.value]))
  return `${map.year}-${map.month}-${map.day} ${map.hour}:${map.minute}:${map.second}`
}

async function replaceTimestampInHtmlFiles(rootDir, timestamp) {
  const candidates = []
  const walk = async (dir) => {
    const entries = await readdir(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = resolve(dir, entry.name)
      if (entry.isDirectory()) {
        await walk(fullPath)
      } else if (entry.isFile() && entry.name.endsWith('.html')) {
        candidates.push(fullPath)
      }
    }
  }

  await walk(rootDir)

  for (const filePath of candidates) {
    const source = await readFile(filePath, 'utf8')
    if (!source.includes('__BUILD_TIMESTAMP__')) continue
    await writeFile(filePath, source.replaceAll('__BUILD_TIMESTAMP__', timestamp), 'utf8')
  }
}

// https://vite.dev/config/
export default defineConfig({
  base: '/',
  plugins: [react(),
    {
      name: 'html-timestamp',
      transformIndexHtml(html) {
        return html.replaceAll('__BUILD_TIMESTAMP__', buildTimestamp())
      },
      generateBundle(_, bundle) {
        const timestamp = buildTimestamp()
        Object.values(bundle).forEach(file => {
          if (file.type === 'asset' && file.fileName.endsWith('.html')) {
            file.source = file.source.replaceAll('__BUILD_TIMESTAMP__', timestamp)
            // Timestamp generated by vite
          }
        })
      },
      async closeBundle() {
        const timestamp = buildTimestamp()
        await replaceTimestampInHtmlFiles(resolve(process.cwd(), 'dist'), timestamp)
        const fontOutputDir = resolve(process.cwd(), 'dist/src/assets/fonts')
        await mkdir(fontOutputDir, { recursive: true })
        await copyFile(
          resolve(process.cwd(), 'src/assets/fonts/ExplorerCondensed-Bold.woff2'),
          resolve(fontOutputDir, 'ExplorerCondensed-Bold.woff2')
        )
      }
    }
  ],
})
